import res from '../Resources/index.js';

const comments = [
    {
        id: 1,
        avatar: res.images.commentAvatars[0],
        user_id: 'uid1',
        user_name: 'user 1',
        first_name: 'Thanh',
        last_name: 'Tran Tri',
        content: 'bộ phim này rất hay, mong ad cập nhật thêm nhé ! This Tv show is so interesting! , I hope you update more ! ',
        like_number: 23,
        is_liked: false,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 2,
        avatar: res.images.commentAvatars[2],
        user_id: 'uid2',
        user_name: 'user 2',
        first_name: 'Authum',
        last_name: 'Davan',
        content: 'bài hát quá hay..lắc lư ',
        like_number: 21,
        is_liked: true,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 3,
        avatar: res.images.commentAvatars[3],
        user_id: 'uid3',
        user_name: 'user 3',
        first_name: 'Anh',
        last_name: 'Nguyen Quoc',
        content: 'các bạn ơi! Sao hình ảnh không nét nhỉ? Hay do máy của mình... Cách chỉnh hình ảnh nét thì phải làm sao ạ? ',
        like_number: 20,
        is_liked: false,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
    },
    {
        id: 4,
        avatar: res.images.commentAvatars[4],
        user_id: 'uid3',
        user_name: 'user 3',
        first_name: 'Osamu',
        last_name: 'Dazai',
        content: ':D phim rất hay, tjks anh chị admin ạ :p ',
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
        like_number: 20,
        is_liked: true,
    },
    {
        id: 5,
        is_liked: true,
        username: 'phuongnl',
        avatar: res.images.commentAvatars[5],
        first_name: 'Heiller',
        last_name: 'Beiker',
        content: 'can u guys plz fix this ???? the subtitles are not right with the sounds and also the videos from episode 15 ->20. Thank advance',
        like_number: 3,
        createdAt: '31/12/2017',
        updateAt: '31/12/2017',
        userId: 1,
        filmId: 2,
    }
]

export const filmDetailComments = [comments[1], comments[2], comments[0], comments[3]];
export const episodeComments = [comments[0], comments[3], comments[4]];