import Res from '../Resources/index.js'

export const episodes = [
    {
        id: 1,
        user_watch_episode: null,
        number: 1,
        name: 'Tập 1',
        video: Res.images.tip,
        link_video: Res.video.theFlash,
        sub: Res.video.flashSub,
        eng_sub: null,
        vie_sub: null,
        film_id: 1,
    },
    {
        id: 2,
        user_watch_episode: null,
        number: 1,
        name: 'Tập 1',
        video: Res.images.tip,
        link_video: Res.video.theFlash,
        sub: Res.video.flashSub,
        eng_sub: null,
        vie_sub: null,
        film_id: 2,
    },
    {
        id: 3,
        user_watch_episode: null,
        number: 1,
        name: 'Tập 2',
        video: Res.images.tip,
        link_video: Res.video.theFlash,
        sub: Res.video.flashSub,
        eng_sub: null,
        vie_sub: null,
        film_id: 2,
    },
    {
        id: 4,
        user_watch_episode: null,
        number: 1,
        name: 'Tập 1',
        video: Res.images.tip,
        link_video: Res.video.theFlash,
        sub: Res.video.flashSub,
        eng_sub: null,
        vie_sub: null,
        film_id: 3,
    },
    {
        id: 5,
        user_watch_episode: null,
        number: 1,
        name: 'Tập 2',
        video: Res.images.tip,
        link_video: Res.video.theFlash,
        sub: Res.video.flashSub,
        eng_sub: null,
        vie_sub: null,
        film_id: 3,
    },
]