import res from '../Resources/index'
export const films = [
    {
        id: 1,
        is_saved: false,
        is_liked: true,
        english_name: "The flash - Season 1",
        vietnamese_name: "Tia chớp - Mùa 1",
        difficult_level: 3,
        description: "Trong một lần tại Starling City, Barry đã vô tình bị ảnh hưởng bởi vụ nổ phòng thí nghiệm của S.T.A.R khiến anh bị bất tỉnh nhiều ngày trong bệnh viện. Khi tỉnh dậy, anh ta đã phát hiện ra rằng mình có khả năng đặc biệt đó là tăng tốc độ cơ thể và di chuyển siêu nhanh. Kể từ đây, huyền thoại về người anh hùng Flash bắt đầu!",
        thumbnail: res.filmImage.theFlash,
        average_score: 3.0,
        review_number: 2,
        duration: "25 phút",
        episode_number: 23,
        episode_count: 2,
        view_number: 107,
    },
    {
        id: 2,
        is_saved: true,
        is_liked: false,
        english_name: "The big bang theory - Season 1",
        vietnamese_name: "Vụ nổ lớn - Phần 1",
        difficult_level: 1,
        description: "Là câu chuyện của 4 chàng trai luôn tự cho mình là những nhà thiên tài khoa học với những mối quan hệ trong cuộc sống của 4 chàng ngày càng trở nên căng thẳng và rắc rối hơn: Mối quan hệ của Leonard và Penny thì ngày càng tồi tệ, họ đã nhanh cóng chia tay, trong khi mối quan hệ của Sheldon với Penny lại từ từ bắt đầu, Howard thì vẫn nỗ lực quyến rũ phụ nữ và bắt đầu mối quan hệ ngắn với Leslie, còn Rajesh lại phải giải quyết hậu quả mình đã gây ra cho Penny…cùng với sự xuất hiện của một cô gái tóc vàng hấp dẫn, người đã làm Penny mất sự chú ý của các chàng trai.",
        thumbnail: res.filmImage.bigBang,
        average_score: 4.0,
        review_number: 0,
        duration: "25 phút",
        episode_number: 23,
        episode_count: 0,
        view_number: 100,
    },
    {
        id: 3,
        is_saved: true,
        is_liked: false,
        english_name: "Rise of the guardians",
        vietnamese_name: "Cuộc trỗi dậy của các vệ thần",
        difficult_level: 3,
        description: "Sự trỗi dậy của các Vệ thần là một bộ phim hoạt hình giả tưởng/phiêu lưu 3D dựa trên loạt sách The Guardians of Childhood của William Joyce và phim ngắn The Man in the Moon của Joyce và Reel FX",
        thumbnail: res.filmImage.rise,
        average_score: 2.38,
        review_number: 4,
        duration: "90 phút",
        episode_number: 1,
        episode_count: 1,
        view_number: 30,
    },
    {
        id: 4,
        is_saved: false,
        is_liked: true,
        english_name: "Rio (2011)",
        vietnamese_name: "Vẹt đuôi dài (2011)",
        difficult_level: 3,
        description: "Blu là chú chim Macaw thuần hóa và chưa bao giờ tập bay, sống một cuộc sống thoải mái với người bạn thân Linda cùng cậu chủ. Blu và Linda đều tưởng Blu là cá thể duy nhất còn sót lại của loài Macaw, nhưng rồi họ phát hiện ra còn một “cô” Macaw cái tại Rio de Janeiro, cả hai quyết định thực hiện của hành trình mạo hiểm để tìm Jewel, cô Macaw của Blu. Không may khi tới Rio, Blu và Jewel bị bắt cóc bởi một nhóm buôn lậu thú, với sự khôn ngoan của Jewel và sự giúp sức của các chú chim thành phố. Blu đã trốn thoát, cùng sự trợ giúp của những người bạn mới, chú chim Macaw sẽ tìm cách học bay, giải cứu người bạn Linda và dạy cho bọn buôn lậu một bài học.",
        thumbnail: res.filmImage.rio,
        average_score: 2.5,
        review_number: 1,
        duration: "90 phút",
        episode_number: 1,
        episode_count: 1,
        view_number: 15,
    },
    {
        id: 5,
        is_saved: true,
        is_liked: true,
        english_name: "Mom - Season 1",
        vietnamese_name: "Mẹ - Mùa 1",
        difficult_level: 1,
        description: "Là câu chuyện hài hước kể về quá trình tìm lại cuộc sống của Christy - 1 người mẹ độc thân mới tỉnh dậy sau chuỗi ngày dài nghiện ngập rượu của mình, cô đang phải tìm cách quay trở lại cuộc sống của chính mình để giải quyết những vấn đề rắc rối của hai đứa trẻ đang tuổi mới lớn cũng như gây dựng lại mối quan hệ với những người xung quanh trong thung lũng Napa",
        thumbnail: res.filmImage.mom,
        average_score: 3.8,
        review_number: 0,
        duration: "25 phút",
        episode_number: 23,
        episode_count: 2,
        view_number: 50,
    },
    {
        id: 6,
        is_saved: false,
        is_liked: false,
        english_name: "Hannah Montana - Season 1",
        vietnamese_name: "Hannah Montana - Mùa 1",
        difficult_level: 3,
        description: "Một nữ sinh trung học sống 2 đời sống : một là Miley Stewart, nữ sinh trung học bình thường, mặt kia là Hannah Montana, ca sĩ nhạc Rock được khán giả rất yêu thích. Tuy nhiên sự nổi tiếng của Hannah khiến cuộc sống của Miley trở nên quá tải. Cha cô khuyên cô nên về quê tại vùng Crowley Corners, Tennessee để tìm thấy hạnh phúc đích thực trong cuộc sống. Nhưng liệu xa rời sân khâu hào nhoáng, Miley có tìm được hạnh phúc như cha cô nghĩ?",
        thumbnail: res.filmImage.hannah,
        average_score: 2.83,
        review_number: 3,
        duration: "25 phút",
        episode_number: 26,
        episode_count: 2,
        view_number: 107,
    },
    {
        id: 7,
        is_saved: false,
        is_liked: false,
        english_name: "Friends - Season 1",
        vietnamese_name: "Những người bạn - Mùa 1",
        difficult_level: 2,
        description: "Phim Friends là bộ phim hài rất nổi tiếng ở Mỹ gồm 10 seasons được dùng trong hầu hết các trung tâm dạy tiếng anh ở nước Mỹ như là một công cụ trong việc nâng cao về việc luyện nghe nói, phản xạ trong việc học tiếng anh dành cho sinh viên nước ngoài. Một điều quan trọng chính là bộ phim friends phụ đề tiếng anh đã mang lại cho khán giả các nước khác một cái nhìn cực kì chính xác, chân thật về xã hội Mỹ, về phong cách sống, cách xử sự của người Mỹ",
        thumbnail: res.filmImage,
        average_score: 0.0,
        review_number: 0,
        duration: "25 phút",
        episode_number: 24,
        episode_count: 2,
        view_number: 203,
    },
    {
        id: 8,
        is_saved: false,
        is_liked: false,
        english_name: "Extr@",
        vietnamese_name: "Extr@",
        difficult_level: 2,
        description: "Bộ phim extra English gồm 30 tập đây là một phim học tiếng Anh được rất nhiều người ưa thích trên thế giới. Ra đời sau các tập phim Friends trước, Phim extra song ngữ Anh Việt dường như ưu việt hơn về mặt học tiếng Anh giao tiếp, nhất là những người mới bắt đầu học. Học tiếng anh qua phim extra giúp người mới bắt đầu học trau dồi được kỹ năng phát âm tiếng anh cùng một số câu giao tiếp đơn giản được biên soạn kỹ càng trong phim extra này. Hãy cùng studyphim.vn trải nghiệm hơn 30 tập phim extra phụ đề tiếng anh với sub song ngữ thông minh nhé.",
        thumbnail: res.filmImage.extra,
        average_score: 3.25,
        review_number: 3,
        duration: "25 phút",
        episode_number: 30,
        episode_count: 2,
        view_number: 107,
    },
    {
        id: 9,
        is_saved: true,
        is_liked: true,
        english_name: "How I met your mother - Season 1",
        vietnamese_name: "Khi bố gặp mẹ - Mùa 1",
        difficult_level: 1,
        description: "Xem phim how i met your mother là câu chuyện được nhân vật chính - Ted Mosby kể lại cho 2 đứa con của mình về câu chuyện tình của bố mẹ chúng. Khi anh chàng 27 tuổi, Ted cảm thấy muốn kết hôn sau khi cậu bạn cùng phòng, Marshall đính hôn với cô bạn thân từ thời đại học của anh, Lily sau 9 năm hẹn hò. Với sự giúp đỡ của 'chuyên gia tán gái' Barney, Ted đã bước vào cuộc tìm kiếm “một nửa” của mình. Bộ phim vô cùng hài hước và là nguồn tài liệu để học nói tiếng anh cực kì hiệu quả.",
        thumbnail: res.filmImage.mother,
        average_score: 3.13,
        review_number: 2,
        duration: "25 phút",
        episode_number: 22,
        episode_count: 2,
        view_number: 300,
    },
];

export const newestFilms = films.slice(0, 6);
export const mostViewedFilm = [films[0], films[3], films[4], films[8], films[6]];
export const promotes = [films[1], films[3], films[5]];
export const historyFilms = [films[0], films[2], films[3], films[4], films[8]];
